/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import domen.Radnik;
import domen.Ucinak;
import domen.VrstaPosla;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.EmptyStackException;
import java.util.MissingResourceException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import logika.Kontroler;
import model.ModelTabeleUcinak;

/**
 *
 * @author User
 */
public class FrmGlavna extends javax.swing.JFrame {

    /**
     * Creates new form FrmGlavna
     */
    public FrmGlavna() {
        initComponents();
        srediTabelu();
        ucitajVrstePosla();
        ucitajRadnike();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButtondodajucinak = new javax.swing.JButton();
        jButtonobrisiucinak = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableucinci = new javax.swing.JTable();
        jButtonsacuvajucinkeradnika = new javax.swing.JButton();
        jComboBoxvrstaposla = new javax.swing.JComboBox();
        jComboBoxradnici = new javax.swing.JComboBox();
        jTextFieldbrojsati = new javax.swing.JTextField();
        jTextFielddatum = new javax.swing.JTextField();
        jButtonizbrisisve = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Vrsta posla:");

        jLabel3.setText("Radnik: ");

        jLabel4.setText("Broj sati:");

        jLabel5.setText("Datum (dd.MM.yyyy):");

        jButtondodajucinak.setText("Dodaj učinak");
        jButtondodajucinak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtondodajucinakActionPerformed(evt);
            }
        });

        jButtonobrisiucinak.setText("Obriši učinak");
        jButtonobrisiucinak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonobrisiucinakActionPerformed(evt);
            }
        });

        jTableucinci.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableucinci);

        jButtonsacuvajucinkeradnika.setText("Sačuvaj učinke radnika");
        jButtonsacuvajucinkeradnika.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonsacuvajucinkeradnikaActionPerformed(evt);
            }
        });

        jComboBoxvrstaposla.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxvrstaposla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxvrstaposlaActionPerformed(evt);
            }
        });

        jComboBoxradnici.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxradnici.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxradniciActionPerformed(evt);
            }
        });

        jTextFielddatum.setText(" ");

        jButtonizbrisisve.setText("Izbrisi sve unete ucinke");
        jButtonizbrisisve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonizbrisisveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtondodajucinak)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxvrstaposla, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBoxradnici, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonobrisiucinak)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jTextFieldbrojsati)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonsacuvajucinkeradnika)
                        .addGap(27, 27, 27)
                        .addComponent(jButtonizbrisisve)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFielddatum)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2))
                    .addComponent(jComboBoxvrstaposla))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBoxradnici, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldbrojsati, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jTextFielddatum, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtondodajucinak)
                    .addComponent(jButtonobrisiucinak))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 128, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonsacuvajucinkeradnika, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonizbrisisve, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonobrisiucinakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonobrisiucinakActionPerformed
        int red = jTableucinci.getSelectedRow();
        ModelTabeleUcinak mtu = (ModelTabeleUcinak) jTableucinci.getModel();
        try {
            mtu.obrisi(red);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Niste selektovali red koji zelite da obrisete!", "Greska", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonobrisiucinakActionPerformed

    private void jComboBoxradniciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxradniciActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxradniciActionPerformed

    private void jButtondodajucinakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtondodajucinakActionPerformed
        VrstaPosla vp = (VrstaPosla) jComboBoxvrstaposla.getSelectedItem();
        Radnik r = (Radnik) jComboBoxradnici.getSelectedItem();
        String brSati = null;
        String dat = null;

        int brojSati = -1;
        try {
            brSati = jTextFieldbrojsati.getText();
            for (int i = 0; i < brSati.length(); i++) {
                if (!Character.isDigit(brSati.charAt(i))) {
                    JOptionPane.showMessageDialog(this, "Mora broj, a ne slovo!");
                    return;
                }

            }
            brojSati = Integer.parseInt(brSati);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Niste uneli broj sati", "Greska", JOptionPane.ERROR_MESSAGE);
        }
        SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy");
        Date datum = null;
        try {
            dat = jTextFielddatum.getText();
            if (dat.isEmpty()) {
                throw new IllegalArgumentException();
            }
            datum = sdf.parse(dat);

        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(this, "Niste uneli datum", "Greska", JOptionPane.ERROR_MESSAGE);
        } catch (ParseException pe) {
            JOptionPane.showMessageDialog(this, "Pogresno unet format datuma!", "Greska", JOptionPane.ERROR_MESSAGE);
        }

        if (brojSati != -1 && datum != null) {
            Ucinak u = new Ucinak(-1, brojSati, datum, vp, r);
            ModelTabeleUcinak mtu = (ModelTabeleUcinak) jTableucinci.getModel();
            mtu.dodaj(u);
        }

    }//GEN-LAST:event_jButtondodajucinakActionPerformed

    private void jButtonsacuvajucinkeradnikaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonsacuvajucinkeradnikaActionPerformed
//        ModelTabeleUcinak mtu=(ModelTabeleUcinak)jTableucinci.getModel();
//        ArrayList<Ucinak> listaUcinaka=mtu.vratiListeucinaka();
//        
//        boolean uspesno=false;
//        uspesno=Kontroler.getInstance().dodajListuucinaka(listaUcinaka);
//        if (uspesno) {
//            JOptionPane.showMessageDialog(this, "Sve sacuvano");
//        }
//        else JOptionPane.showMessageDialog(this, "Nista nije sacuvano! Probaj opet!");
//                
        ModelTabeleUcinak mtu = (ModelTabeleUcinak) jTableucinci.getModel();
        ArrayList<Ucinak> listaUcinaka = mtu.vratiListeucinaka();
        boolean uspesno = Kontroler.getInstance().sacuvajListu(listaUcinaka);
        if (uspesno) {
            JOptionPane.showMessageDialog(this, "SVEE je sacuvano");
        }else{
        JOptionPane.showMessageDialog(this, "Nistaa nije sacuvano kak' treba!");}

    }//GEN-LAST:event_jButtonsacuvajucinkeradnikaActionPerformed

    private void jComboBoxvrstaposlaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxvrstaposlaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxvrstaposlaActionPerformed

    private void jButtonizbrisisveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonizbrisisveActionPerformed
        boolean uspesno = false;
        uspesno = Kontroler.getInstance().obrisiSve();
        if (uspesno) {
            JOptionPane.showMessageDialog(this, "Sve je uspesnoo obrisano!", "Info", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Nista nije uspesnoo obrisano!", "Info", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonizbrisisveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmGlavna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmGlavna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmGlavna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmGlavna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmGlavna().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtondodajucinak;
    private javax.swing.JButton jButtonizbrisisve;
    private javax.swing.JButton jButtonobrisiucinak;
    private javax.swing.JButton jButtonsacuvajucinkeradnika;
    private javax.swing.JComboBox jComboBoxradnici;
    private javax.swing.JComboBox jComboBoxvrstaposla;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableucinci;
    private javax.swing.JTextField jTextFieldbrojsati;
    private javax.swing.JTextField jTextFielddatum;
    // End of variables declaration//GEN-END:variables

    private void srediTabelu() {
        ModelTabeleUcinak mtu = new ModelTabeleUcinak();
        jTableucinci.setModel(mtu);
    }

    private void ucitajVrstePosla() {

        jComboBoxvrstaposla.removeAllItems();
        ArrayList<VrstaPosla> listaVrstiPosla = Kontroler.getInstance().vratiListeVrstiPosla();
        for (VrstaPosla vp : listaVrstiPosla) {
            jComboBoxvrstaposla.addItem(vp);
        }
    }

    private void ucitajRadnike() {
        jComboBoxradnici.removeAllItems();
        ArrayList<Radnik> listaRadnika = Kontroler.getInstance().vratiListuRadnika();
        for (Radnik radnik : listaRadnika) {
            jComboBoxradnici.addItem(radnik);
        }
    }

}
